### ISSUE TITLE
Inspect fails to retrieve IP address when inside a privileged Docker container

### ISSUE THREAD

**Issue by ipmb** [projectatomic/libpod#679]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

**Steps to reproduce the issue:**

```
export NAME=redis
podman run -d --name=$NAME redis:4-alpine
podman inspect --type=container $NAME | jq -r '.[] | select(.State.Running).NetworkSettings.IPAddress'
```

**Describe the results you received:**

```
ERRO[0000] error getting container "48bf1ed1672dd2e0620a068de32ce1930d9f32cb47532b59daffe00ab1c0c48f" IP: error retrieving network status of container 48bf1ed1672dd2e0620a068de32ce1930d9f32cb47532b59daffe00ab1c0c48f: Unexpected command output nsenter: failed to execute ip: No such file or directory
 with error: exit status 1
```

**Describe the results you expected:**

The IP address of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Strangely, this works fine, so I'm not sure what the message about failing to execute `ip` is:

```
/usr/bin/podman exec $NAME ip addr show eth0 | /bin/grep "inet " | /usr/bin/awk '{print $2}' | /usr/bin/cut -f1 -d'/'
```

I have only been able to see this issue when it I run podman inside a Docker container. On a "real" machine, `inspect` works fine.

**Output of `podman version`:**

```
Version:       0.4.4-dev
Go Version:    go1.10
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 163012608
  MemTotal: 2096066560
  SwapFree: 923910144
  SwapTotal: 1073737728
  arch: amd64
  cpus: 2
  hostname: util-kitchen
  kernel: 4.9.87-linuxkit-aufs
  os: linux
  uptime: 1h 31m 9.77s (Approximately 0.04 days)
insecure registries:
  registries: null
registries:
  registries:
  - docker.io
store:
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions:
  - vfs.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
